#!/bin/sh

case "$1" in
	remove|purge|abort-install|abort-upgrade)
		# This package is being removed, but its configuration has not yet
		# been purged.

		# Disable service on removal
		if [ -d /run/systemd/system ]; then
			# Systemd
			systemctl disable stud.service >/dev/null 2>&1 || true
			systemctl stop stud.service >/dev/null 2>&1 || true
		else
			# SysV init
			if [ -x /usr/sbin/update-rc.d ]; then
				update-rc.d -f stud remove >/dev/null 2>&1 || true
			fi
		fi
	
		# remove rundir
		rm -rf /var/run/stud >/dev/null 2>&1

		# remove config dir
		rm -rf /etc/stud >/dev/null 2>&1

		;;
	
	disappear)
		;;

	upgrade)
		;;

	failed-upgrade)
		;;

	*) echo "$0: didn't understand being called with \`$1'" 1>&2
		exit 1;;
esac

exit 0

# EOF
