#!/bin/sh

case $1 in
	# Configure this package.  If the package must prompt the user for
	# information, do it here.
	configure)
		mkdir -p /var/run/stud
		
		# Enable service on installation
		if [ -d /run/systemd/system ]; then
			# Systemd
			systemctl enable stud.service >/dev/null 2>&1 || true
			echo "Systemd service enabled. Use: systemctl start stud"
		else
			# SysV init
			if [ -x /usr/sbin/update-rc.d ]; then
				update-rc.d stud defaults >/dev/null 2>&1 || true
				echo "Init.d service enabled. Use: service stud start"
			fi
		fi
		
		# Display installation information
		echo
		echo "stud installation complete!"
		echo
		echo "Configuration files have been installed to:"
		echo "  /etc/stud/stud.conf.example    - Example configuration"
		echo "  /etc/stud/generate-selfsigned-cert.sh - Certificate generation script"
		echo "  /etc/stud/README.TXT           - Quick start guide"
		echo
		echo "Quick start:"
		echo "  1. Generate a certificate:"
		echo "     cd /etc/stud"
		echo "     ./generate-selfsigned-cert.sh yourdomain.com /etc/ssl/stud"
		echo
		echo "  2. Create a configuration:"
		echo "     cp /etc/stud/stud.conf.example /etc/stud/myapp.conf"
		echo "     edit /etc/stud/myapp.conf"
		echo
		echo "  3. Start stud:"
		echo "     stud --config=/etc/stud/myapp.conf"
		echo "     # or use service: systemctl start stud"
		echo
		echo "For more examples, see /usr/share/doc/stud/examples/"
		echo
		;;

	# Back out of an attempt to upgrade this package FROM THIS VERSION
	# to version $2.  Undo the effects of "prerm upgrade $2".
	abort-upgrade)
		;;

	# Back out of an attempt to remove this package, which was due to
	# a conflict with package $3 (version $4).  Undo the effects of
	# "prerm remove in-favour $3 $4".
	abort-remove)
		;;

	# Back out of an attempt to deconfigure this package, which was
	# due to package $6 (version $7) which we depend on being removed
	# to make way for package $3 (version $4).  Undo the effects of
	# "prerm deconfigure in-favour $3 $4 removing $6 $7".
	abort-deconfigure)
		;;

	*)
		echo "$0: didn't understand being called with \`$1'" 1>&2
		exit 1;
		;;

esac

if command -v systemctl >/dev/null 2>&1 && systemctl is-active stud.service >/dev/null 2>&1; then
	echo 
	echo "              !!!! WARNING !!!!"
	echo 
	echo "stud is running, you should restart it."
	echo
elif service stud status >/dev/null 2>&1; then
	echo 
	echo "              !!!! WARNING !!!!"
	echo 
	echo "stud is running, you should restart it."
	echo
fi

# EOF
