#!/bin/sh

case "$1" in
	remove|purge|abort-install|abort-upgrade)
		# This package is being removed, but its configuration has not yet
		# been purged.

		# shutdown service
		if command -v systemctl >/dev/null 2>&1; then
			systemctl stop stud.service >/dev/null 2>&1 || true
		else
			service stud stop >/dev/null 2>&1 || true
		fi

		;;
	
	disappear)
		;;

	upgrade)
		;;

	failed-upgrade)
		;;

	*) echo "$0: didn't understand being called with \`$1'" 1>&2
		exit 1;;
esac

exit 0

# EOF
